# Generated by Django 4.2.30 on 2026-08-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_healthreading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='taken',
        ),
        migrations.AddField(
            model_name='medication',
            name='taken_days',
            field=models.CharField(blank=True, default='', help_text='Comma-separated weekdays the dose was taken', max_length=100),
        ),
    ]
