# Generated by Django 4.2.30 on 2026-08-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_medication_taken_medication_taken_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='times_of_day',
            field=models.CharField(blank=True, default='', help_text='Comma-separated times like 08:00,14:00,20:00', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(choices=[('bimeh_salamat', 'Bimeh Salamat Iranian (Iran Health Insurance)'), ('bimeh_tamin_ejtemaei', 'Social Security Insurance'), ('bimeh_niroo_mosallah', 'Armed Forces Insurance'), ('bimeh_roostaei_ashayer', 'Rural & Nomadic Insurance'), ('bimeh_komite_emdad', 'Imam Khomeini Relief Committee Insurance'), ('bimeh_khadamat_darmani', 'Medical Services Insurance (Gov. Employees)'), ('bimeh_iran', 'Iran Insurance'), ('bimeh_asia', 'Asia Insurance'), ('bimeh_dana', 'Dana Insurance'), ('bimeh_parsian', 'Parsian Insurance'), ('bimeh_novin', 'Novin Insurance'), ('bimeh_saman', 'Saman Insurance'), ('bimeh_razi', 'Razi Insurance')], max_length=30),
        ),
    ]
