# Generated by Django 4.2.30 on 2026-08-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_medication_times_of_day_alter_patient_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='password_5digit',
        ),
        migrations.AddField(
            model_name='patient',
            name='password_hash',
            field=models.CharField(default='', max_length=128),
        ),
    ]
