# Generated by Django 4.2.30 on 2026-08-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_patient_password_5digit_patient_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='accepted_insurance',
            field=models.CharField(blank=True, default='', help_text='Comma-separated insurance keys the doctor accepts', max_length=500),
        ),
    ]
