# Generated by Django 4.2.30 on 2026-08-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_doctor_accepted_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Short description of what the doctor treats'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='medical_id',
            field=models.CharField(default='1000', help_text='Unique medical ID (e.g., 1001)', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default='General', help_text='Medical specialty (e.g., Cardiology)', max_length=100),
        ),
    ]
