# Generated by Django 4.2.30 on 2026-08-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_doctor_description_doctor_medical_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, default='', help_text='Comma-separated insurance keys', max_length=500),
        ),
    ]
