# Generated by Django 4.2.30 on 2026-08-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_patientvisit_prescription_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='patient',
            name='disease_history',
            field=models.TextField(blank=True, default=''),
        ),
    ]
