# Generated by Django 4.2.30 on 2026-08-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_patientrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='patient_records/%Y/%m/'),
        ),
    ]
