# Generated by Django 4.2.30 on 2026-08-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(help_text='Patient phone (Iranian 09... or +countrycode...)', max_length=24),
        ),
    ]
