# Generated by Django 4.2.30 on 2026-08-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_appointment_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='Telegram chat id to receive bot reminders', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_link_token',
            field=models.CharField(blank=True, default=None, help_text='One-time token used to connect a Telegram account', max_length=64, null=True, unique=True),
        ),
    ]
