# Generated by Django 4.2.30 on 2026-08-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_telegram_chat_id_user_telegram_link_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_active',
            field=models.BooleanField(default=False, help_text='This account is the active one for its shared Telegram chat'),
        ),
    ]
