# Generated by Django 4.2.30 on 2026-08-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_doctoroffday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_link_token',
            field=models.CharField(blank=True, default=None, help_text='One-time token used to connect a Telegram account', max_length=64, null=True),
        ),
    ]
