# Generated by Django 4.2.30 on 2026-08-30 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_fix_telegram_link_token_unique'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
UPDATE accounts_user
SET telegram_link_token = NULL
WHERE telegram_link_token = '';
""",
            reverse_sql="""
UPDATE accounts_user
SET telegram_link_token = ''
WHERE telegram_link_token IS NULL;
"""
        ),
    ]
