# Generated by Django 4.2.30 on 2026-09-07 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_fix_telegram_link_token_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('class', '📚 Class / Course'), ('work', '💼 Work'), ('appointment', '🏥 Other Clinic Appointment'), ('personal', '🏠 Personal / Family'), ('exercise', '🏃 Exercise / Sport'), ('other', '📌 Other')], default='other', max_length=20)),
                ('day_of_week', models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, default='', help_text='e.g., "Yoga Studio", "Dr. Smith Cardiology"', max_length=200)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color for calendar display', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='accounts.patient')),
            ],
            options={
                'verbose_name': 'Schedule Item',
                'verbose_name_plural': 'Schedule Items',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
