# Generated by Django 4.2.30 on 2026-09-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_patientschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email_encrypted',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_encrypted',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
